{
 "title": "Main Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ProviderName",
    "query": "SELECT DISTINCT ProviderName FROM proxy_requests"
   }
  ]
 },
 "panels": [
  {
   "title": "Response time MS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toStartOfInterval(RequestTime, INTERVAL 5 minute) AS time,\r\n    ProviderName,\r\n    Pool,\r\n    AVG(TimeTaken) AS avg_time_taken\r\nFROM\r\n    proxy_requests\r\nWHERE\r\n    RequestTime BETWEEN now() - INTERVAL 1 week AND now()\r\n    AND Success = 1\r\nGROUP BY\r\n    time, ProviderName, Pool\r\nORDER BY\r\n    time, Pool;  -- You can also add ProviderName here if you want to order by it as well\r\n"
    }
   ]
  },
  {
   "title": "Failure rate ",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "WITH FilteredRequests AS (\r\n    SELECT \r\n        ProviderName,\r\n        Pool,\r\n        Success,\r\n        ErrorMessage\r\n    FROM proxy_requests\r\n    WHERE ErrorMessage NOT LIKE '%cannot assign requested address%'\r\n),\r\nFailureStats AS (\r\n    SELECT \r\n        ProviderName,\r\n        Pool,\r\n        COUNT(*) AS TotalRequests,\r\n        SUM(CASE WHEN Success = 0 THEN 1 ELSE 0 END) AS FailedRequests\r\n    FROM FilteredRequests\r\n    GROUP BY ProviderName, Pool\r\n)\r\nSELECT \r\n    ProviderName,\r\n    Pool,\r\n    TotalRequests,\r\n    FailedRequests,\r\n    (FailedRequests * 100.0 / TotalRequests) AS FailureRate\r\nFROM FailureStats\r\nORDER BY FailureRate DESC;\r\n"
    }
   ]
  },
  {
   "title": "Unique Ips per provider",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    ProviderName,\n    COUNT(DISTINCT IP) AS UniqueIPs\nFROM\n    proxy_requests\nWHERE\n    Success = 1\nGROUP BY\n    ProviderName\nORDER BY\n    UniqueIPs DESC"
    }
   ]
  },
  {
   "title": "IPv6 Subnet Identifier",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ProviderName,\r\n    concat(arrayElement(splitByChar(':', IP), 1), ':', \r\n           arrayElement(splitByChar(':', IP), 2)) AS IPv6Prefix,\r\n    COUNT(DISTINCT IP) AS UniqueIPs\r\nFROM proxy_requests\r\nWHERE position(IP, ':') > 0 -- Only include IPv6 addresses\r\n  AND Success = 1 -- Only consider successful requests\r\nGROUP BY ProviderName, IPv6Prefix\r\nHAVING COUNT(DISTINCT IP) > 5000 -- Filter to include only prefixes with more than 5000 unique IPs\r\nORDER BY ProviderName, UniqueIPs DESC\r\n"
    }
   ]
  },
  {
   "title": "Reused Ips %",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH IPStats AS (\r\n    SELECT \r\n        ProviderName,\r\n        Pool,\r\n        COUNT(*) AS TotalRequests,\r\n        COUNT(DISTINCT IP) AS UniqueIPs\r\n    FROM proxy_requests\r\n    WHERE Success = 1\r\n    GROUP BY ProviderName, Pool\r\n)\r\nSELECT \r\n    ProviderName,\r\n    Pool,\r\n    UniqueIPs,\r\n    TotalRequests,\r\n    TotalRequests - UniqueIPs AS ReusedIPs\r\nFROM IPStats\r\nORDER BY ReusedIPs DESC;\r\n"
    }
   ]
  }
 ]
}