FROM golang:1.22
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/flux/main.go ./cmd/flux/main.go
COPY internal ./internal
COPY pkg ./pkg
COPY webserver ./webserver
RUN go build -o runner ./cmd/flux/main.go
RUN chmod +x /app/runner
ENTRYPOINT ["/app/runner"]
