FROM golang:1.22
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/flux/webserver.go ./cmd/flux/webserver.go
COPY internal ./internal
COPY pkg ./pkg
COPY webserver ./webserver
RUN go build -o ui ./cmd/flux/webserver.go
RUN chmod +x /app/ui
ENTRYPOINT ["/app/ui"]
